const PRODUCTS = [
  {
    id: 1,
    name: "Iget Move B50000",
    shortName: "Iget 50K",
    price: 2500,
    puffs: "50,000",
    category: "new",
    image: "images/iget.jpg",
    badge: "New",
    description: "The IGET Move B50000 is a revolutionary dual-flavor disposable vape featuring Type-C charging, dual flavor mode, and an astounding 50,000 puffs. Switch between two incredible flavors in one device.",
    features: ["50,000 Puffs", "Dual Flavor Mode", "Type-C Charging", "Digital Display"],
    flavors: ["Pineapple Ice", "Melon Banana Pineapple", "Triple Melon", "Melon Pineapple Orange", "Red Bull Ice", "Mint Ice", "Raspberry Ice", "Grape Cranberry Blueberry Raspberry", "Cherry Cola Ice", "Blueberry Cranberry Cherry", "Strawberry Banana Ice", "Strawberry Watermelon Ice", "Strawberry Ice", "Strawberry Mango"]
  },
  {
    id: 2,
    name: "Elfbar MoonNight 40K",
    shortName: "Moonlight 40K",
    price: 1900,
    puffs: "40,000",
    category: "new",
    image: "images/moonlight.jpg",
    badge: "New",
    description: "The Elfbar MoonNight 40K features a stunning space-inspired design with 3-level adjustable power and ECO mode for extended sessions. Classic curved design meets futuristic technology.",
    features: ["40,000 Puffs", "3-Level Adjustable Power", "ECO Mode", "Classic Curved Design"],
    flavors: ["Grape Ice", "Watermelon Ice", "Double Mango", "Peach Berry", "Cola Ice", "Kiwi Passion Fruit Guava", "Grape Raspberry", "Miami Mint", "Dragon Strawnana", "Peach Ice", "Mango Peach Watermelon"]
  },
  {
    id: 3,
    name: "Nasty Bolt 50K",
    shortName: "Nasty 50K",
    price: 2300,
    puffs: "50,000",
    category: "new",
    image: "images/nasty.jpg",
    badge: "New",
    description: "Enter the HyperBeast era with the Nasty Bolt 50K. True hyper puff performance with a bold, transparent design that lets you see the action inside. Built for those who demand the most intense experience.",
    features: ["50,000 Puffs", "Hyper Puff Performance", "Digital Display", "Type-C Charging"],
    flavors: ["Cherry Cola", "Grape Ice", "Watermelon Ice", "Strawberry Ice", "Strawberry Watermelon", "Peach Ice", "Mixed Berry", "Raspberry Watermelon", "Blueberry Ice", "Kiwi Passion Fruit Guava", "Berry Mix", "Mango Ice"]
  },
  {
    id: 4,
    name: "Olivebar ICE 50K",
    shortName: "Olive 50K",
    price: 2200,
    puffs: "50,000",
    category: "new",
    image: "images/olive.jpg",
    badge: "New",
    description: "The Olivebar ICE 50000 brings premium cooling technology with 3 ICE modes and a sleek digital display. 950mAh battery ensures long-lasting performance across all your favorite ice flavors.",
    features: ["50,000 Puffs", "3 ICE Modes", "950mAh Battery", "Digital Display"],
    flavors: ["Blackberry Ice", "Blueberry Mint", "Juicy Peach Ice", "Watermelon Berry", "Frozen Grape", "Blueberry Grape Ice", "Frozen Mango", "Strawberry Watermelon Ice"]
  },
  {
    id: 5,
    name: "RandM Tornado 30K",
    shortName: "Tornado 30K",
    price: 1500,
    puffs: "30,000",
    category: "new",
    image: "images/tornado.webp",
    badge: "New",
    description: "The RandM Tornado 30K features iconic alien artwork and a powerful 600mAh battery with dual mesh coil material for incredible flavor. Type-C charging and 30,000 puffs in a compact, artistic design.",
    features: ["30,000 Puffs", "600mAh Battery", "Dual Mesh Coil", "Type-C Charging"],
    flavors: ["Kiwi Passion Fruit Guava", "Strawberry Ice", "Strawberry Watermelon Ice", "Strawberry Raspberry Cherry", "Cherry Berry"]
  },
  {
    id: 6,
    name: "Big Max 50K",
    shortName: "Big Max 50K",
    price: 1700,
    puffs: "50,000",
    category: "bigmax",
    image: "images/bigmax-50k.webp",
    badge: "In Stock",
    description: "The Big Max 50K is a powerhouse disposable delivering an incredible 50,000 puffs of rich, satisfying flavor. Premium build quality and a wide range of flavor options make it a customer favorite.",
    features: ["50,000 Puffs", "Premium Build", "Long Battery Life", "Multiple Flavors"],
    flavors: ["Fizzy Cherry", "Lemon Lime", "Triple Mango", "Fresh Mint", "Watermelon Ice"]
  },
  {
    id: 7,
    name: "Big Max 25K",
    shortName: "Big Max 25K",
    price: 1300,
    puffs: "25,000",
    category: "bigmax",
    image: "images/bigmax-25k.jpg",
    badge: "In Stock",
    description: "All the Big Max quality at 25,000 puffs — perfect for those seeking the classic Big Max experience in a more compact form. Same great flavors, same premium quality.",
    features: ["25,000 Puffs", "Compact Design", "Long Battery Life", "Multiple Flavors"],
    flavors: ["Fizzy Cherry", "Lemon Lime", "Triple Mango", "Fresh Mint", "Watermelon Ice"]
  },
  {
    id: 8,
    name: "Spaceman 50K",
    shortName: "Spaceman 50K",
    price: 2000,
    puffs: "50,000",
    category: "spaceman",
    image: "images/spaceman-50k.jpg",
    badge: null,
    description: "Launch into flavor orbit with the Spaceman 50K. Space-age design meets earth-shattering flavor performance. 50,000 puffs of pure satisfaction with an extraordinary range of flavors.",
    features: ["50,000 Puffs", "Space-Age Design", "Type-C Charging", "Digital Display"],
    flavors: ["Blackberry Razz", "Blue Razz Ice", "Cherry Pomegranate", "Clear (Zero Flavor)", "Fresh Mint", "Juicy Peach Watermelon", "Lemon Pop", "Pink Lemonade", "Root Beer", "Sour Mango Honeydew", "Strawberry Kiwi", "Watermelon Ice", "White Grape Ice"]
  },
  {
    id: 9,
    name: "Spaceman 40K",
    shortName: "Spaceman 40K",
    price: 1800,
    puffs: "40,000",
    category: "spaceman",
    image: "images/spaceman-40k.webp",
    badge: null,
    description: "The Spaceman 40K brings all the stellar design and flavor of the Spaceman series in a 40,000 puff package. Perfect for the flavor astronaut who wants serious performance.",
    features: ["40,000 Puffs", "Space-Age Design", "Type-C Charging", "Digital Display"],
    flavors: ["Blackberry Razz", "Blue Razz Ice", "Cherry Pomegranate", "Clear (Zero Flavor)", "Fresh Mint", "Juicy Peach Watermelon", "Lemon Pop", "Pink Lemonade", "Root Beer", "Sour Mango Honeydew", "Strawberry Kiwi", "Watermelon Ice", "White Grape Ice"]
  },
  {
    id: 10,
    name: "Elfbar 5K",
    shortName: "Elfbar 5K",
    price: 600,
    puffs: "5,000",
    category: "elfbar",
    image: "images/elfbar-5k.jpg",
    badge: "In Stock",
    description: "The classic Elfbar 5K — compact, reliable, and bursting with flavor. The perfect everyday carry for those who want authentic Elfbar quality without compromise.",
    features: ["5,000 Puffs", "Compact Design", "Draw-Activated", "Authentic Elfbar"],
    flavors: ["Kiwi Passion Fruit Guava", "Triple Berry", "Cranberry", "Blue", "Strawberry Banana", "Strawberry Kiwi", "Sour Apple"]
  },
  {
    id: 11,
    name: "TE 6K",
    shortName: "TE 6K",
    price: 450,
    puffs: "6,000",
    category: "small",
    image: "images/te-6k.jpg",
    badge: "Best Value",
    description: "The TE 6K offers incredible value — 6,000 puffs at an unbeatable price. Compact and convenient with satisfying flavor performance that punches well above its price tag.",
    features: ["6,000 Puffs", "Compact & Portable", "Draw-Activated", "Great Value"],
    flavors: ["Strawberry Grapefruit", "Blueberry Pom", "Razz Lemon"]
  },
  {
    id: 12,
    name: "Funky Republic 3K",
    shortName: "Funky 3K",
    price: 300,
    puffs: "3,000",
    category: "small",
    image: "images/funky-3k.webp",
    badge: "Best Value",
    description: "The Funky Republic 3K is the ultimate budget-friendly option without sacrificing flavor quality. Perfect for trying new flavors or as a backup device.",
    features: ["3,000 Puffs", "Ultra Compact", "Draw-Activated", "Funky Flavors"],
    flavors: ["Blue Razz Ice", "Triple Berry Ice", "Miami Mint", "Strawberry Peach Sakura", "Apple Watermelon", "Berry Storm"]
  },
  {
    id: 13,
    name: "Elfbar Ice King 30K",
    shortName: "Elfbar Ice King 30K",
    price: 2000,
    puffs: "30,000",
    category: "elfbar",
    image: "images/elfbar-ice-king-30k.jpg",
    badge: "In Stock",
    description: "The Elfbar Ice King 30K reigns supreme with ice-cold flavor delivery and 30,000 puffs. Built for ice flavor enthusiasts who want the ultimate cooling experience.",
    features: ["30,000 Puffs", "Ice King Technology", "Type-C Charging", "Premium Build"],
    flavors: ["Peach Ice", "Miami Mint", "Kiwi Passion Fruit Guava", "Strawberry Kiwi Ice"]
  },
  {
    id: 14,
    name: "Elfbar 40K",
    shortName: "Elfbar 40K",
    price: 2200,
    puffs: "40,000",
    category: "elfbar",
    image: "images/elfbar-40k.png",
    badge: "In Stock",
    description: "The Elfbar 40K is a premium offering from the world-renowned Elfbar brand. 40,000 puffs of authentic Elfbar flavor excellence with advanced battery and display technology.",
    features: ["40,000 Puffs", "Advanced Technology", "Type-C Charging", "Digital Display"],
    flavors: ["Kiwi Passion Fruit Guava", "Triple Berry", "Cranberry", "Blue", "Strawberry Banana", "Strawberry Kiwi", "Sour Apple"]
  },
  {
    id: 15,
    name: "Elfbar Raya D3 25K",
    shortName: "Elfbar Raya D3 25K",
    price: 1800,
    puffs: "25,000",
    category: "elfbar",
    image: "images/elfbar-raya-d3-25k.jpg",
    badge: "In Stock",
    description: "The Elfbar Raya D3 25K brings Elfbar's signature quality to a 25,000 puff form factor. Elegant design with Raya series exclusive flavors.",
    features: ["25,000 Puffs", "Raya Series Design", "Type-C Charging", "Premium Coil"],
    flavors: ["Grape Ice", "Double Mango", "Watermelon Bubble Gum", "Mango Peach", "Strawberry Grape"]
  },
  {
    id: 16,
    name: "Elfbar Raya D3 Pro 30K",
    shortName: "Elfbar Raya D3 Pro 30K",
    price: 2100,
    puffs: "30,000",
    category: "elfbar",
    image: "images/elfbar-raya-d3-pro-30k.jpg",
    badge: "In Stock",
    description: "The Elfbar Raya D3 Pro 30K is the pinnacle of the Raya series — Pro-grade performance with 30,000 puffs and an expanded flavor lineup including exclusive Lychee Juicy Peach.",
    features: ["30,000 Puffs", "Pro Performance", "Type-C Charging", "Expanded Flavors"],
    flavors: ["Watermelon Ice", "Blueberry Ice", "Peach Ice", "Blackberry Ice", "Blue Razz Ice", "Strawberry Kiwi Ice", "Grape Ice", "Cola Ice", "Lychee Juicy Peach", "Double Mango", "Peach Mango Watermelon", "Blueberry Raspberry Watermelon", "Kiwi Passionfruit Guava"]
  }
];
